### PR TITLE
Right now, we have changed files immediately after open project in An…

### PR DESCRIPTION
**Pull request by rusmonster**
…droid Studio:

dkalita$ git status
HEAD detached at upstream/master
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

```
modified:   .idea/gradle.xml
deleted:    .idea/libraries/jsr305_2_0_3.xml
deleted:    .idea/libraries/material_0_1_3.xml
deleted:    .idea/libraries/recyclerview_v7_22_0_0.xml
deleted:    .idea/libraries/support_annotations_22_0_0.xml
deleted:    .idea/libraries/support_v4_22_0_0.xml
```

This patch fixes it by adding all idea files to .gitignore.

It may be necessary to re-import the project, after merging this commit.

### CODE REVIEW

**Comment by serso** [comment]
I want IDEA files to be in git as I use it from several computers and it's easier for other developers starting to work. I've reported bugs in both [IDEA](https://youtrack.jetbrains.com/issue/IDEA-130490) and [Android Studio](https://code.google.com/p/android/issues/detail?id=172123) bug trackers, hopefully they'll be fixed someday.

**Comment by rusmonster** [comment]
What settings do you store in *.iml and .idea files? Why you cannot do this in gradle files?

It's really a lot of pain for other developers - each time exclude idea's files from commit manually.

**Comment by serso** [comment]
Code style, copyright information, runnable configurations, etc.
Btw in git you can ignore files locally, see [here](http://stackoverflow.com/questions/1753070/git-ignore-files-only-locally) for more details.

**Comment by rusmonster** [comment]
$GIT_DIR/info/exclude file works same as .gitignore. So, it can't help to ignore the file, that is in git's index already.

But it's ok, if you don't want to merge this changes. Each one, who doesn't want exclude idea's files manually, could make this changes in his own fork separately.

**Comment by serso** [comment]
Leave it for now as is, if there are more complains from developers - will be reopened.

**Pull request closed without merging**
